name: South East Fire & Safety
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#929292'
    - '#c1201b'
    - '#770501'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
